/**
 * ============================================================================
 *  CLIENT CONFIGURATION — the single place to edit business details.
 * ============================================================================
 *
 *  To reuse this website for another workshop:
 *    1. Edit the values in this file.
 *    2. Replace assets/source/logo-original.png and run `npm run assets`.
 *    3. Review service copy in src/data/services.ts and blog posts in src/data/blog.ts.
 *
 *  Anything marked `confirmed: false` (or listed in `pendingConfirmation`) is
 *  information the business owner still needs to verify. The site handles these
 *  gracefully: unconfirmed hours are not published in structured data, the
 *  emergency service stays hidden, and so on.
 * ============================================================================
 */

export type DayHours = { day: string; schemaDay: string; opens?: string; closes?: string; closed?: boolean };

export const client = {
  /* ---------------------------------------------------------------- Identity */
  name: "Auto Garage One",
  legalName: "Auto Garage One",
  tagline: "One-Stop Auto Repair & Advanced Services",
  description:
    "Auto Garage One is a car repair and maintenance workshop in B-17, Islamabad offering EFI diagnostics, computerized scanning and tuning, hybrid car repair, AC servicing, brakes, suspension and routine maintenance for drivers across Islamabad and Rawalpindi.",
  foundingYear: 2026,

  /** Public site URL. NEXT_PUBLIC_SITE_URL overrides this at build time. */
  siteUrl: "https://www.autogarageone.pk",

  /* ------------------------------------------------------------------- Logo */
  logo: {
    /** Transparent logo generated by `npm run assets` from assets/source/logo-original.png */
    src: "/brand/logo.webp",
    fallbackPng: "/brand/logo.png",
    /** Intrinsic proportions of the generated logo — keep in sync to avoid distortion. */
    width: 640,
    height: 614,
    alt: "Auto Garage One logo — crossed wrench and hammer above a green shield with pistons and a tyre",
  },

  /* ---------------------------------------------------------------- Contact */
  phone: {
    display: "051-8898534",
    e164: "+92518898534",
  },
  whatsapp: {
    display: "0333-4548008",
    /** International format without "+" — used in https://wa.me/<number> */
    number: "923334548008",
  },
  /** Leave empty until the business provides a monitored email address. */
  email: "",

  address: {
    street: "Shop # 16, NH Arcade, Street No. 10, Block C",
    area: "Multi Gardens B-17",
    city: "Islamabad",
    region: "Islamabad Capital Territory",
    postalCode: "44100",
    country: "Pakistan",
    countryCode: "PK",
  },

  /**
   * Map coordinates. Approximate until confirmed — when `confirmed` is false the
   * coordinates are NOT published in structured data and the map uses the address search.
   */
  /** Pin from the Google Business Profile listing (plus code MRGH+HF). */
  geo: { lat: 33.6763994, lng: 72.8287333, confirmed: true },

  /** Google Business Profile (Maps listing, by cid). */
  googleBusinessProfileUrl: "https://maps.google.com/?cid=17018982629340501133",
  /**
   * "Leave a review" link. Points at the Maps listing (which has a Write a review button);
   * swap in the direct search.google.com/local/writereview?placeid=… link when available.
   */
  googleReviewUrl: "https://maps.google.com/?cid=17018982629340501133",

  /* ------------------------------------------------------------------ Hours */
  hours: {
    /** Set to true only after the owner confirms these times. Confirmed from Google Business Profile. */
    confirmed: true,
    note: "Please call or WhatsApp before visiting — opening hours are being finalised.",
    days: [
      { day: "Monday", schemaDay: "Monday", opens: "09:00", closes: "21:00" },
      { day: "Tuesday", schemaDay: "Tuesday", opens: "09:00", closes: "21:00" },
      { day: "Wednesday", schemaDay: "Wednesday", opens: "09:00", closes: "21:00" },
      { day: "Thursday", schemaDay: "Thursday", opens: "09:00", closes: "21:00" },
      { day: "Friday", schemaDay: "Friday", closed: true },
      { day: "Saturday", schemaDay: "Saturday", opens: "09:00", closes: "21:00" },
      { day: "Sunday", schemaDay: "Sunday", opens: "09:00", closes: "21:00" },
    ] as DayHours[],
  },

  /* ------------------------------------------------------------------ Social */
  social: {
    handle: "@autogarageonepk",
    links: [
      { label: "Facebook", href: "https://www.facebook.com/autogarageonepk" },
      { label: "Instagram", href: "https://www.instagram.com/autogarageonepk" },
      { label: "TikTok", href: "https://www.tiktok.com/@autogarageonepk" },
      { label: "YouTube", href: "https://www.youtube.com/@autogarageonepk" },
    ],
  },

  /* ------------------------------------------------------------ Service area */
  serviceAreas: {
    primary: ["Islamabad", "Rawalpindi"],
    /** Nearby localities mentioned in copy. Keep to areas the workshop genuinely serves. */
    nearby: ["B-17 Multi Gardens", "Sector C-16 & D-17", "Top City-1", "G-13 & G-14", "Golra Mor", "E-11 & F-11", "Tarnol", "Bahria Town & DHA"],
  },

  /* ------------------------------------------------------------------ Offer */
  offer: {
    /** Master switch. Set false to hide every offer banner, card and popup. */
    active: true,
    title: "Free Computerized Scanning & General Vehicle Check-Up",
    shortTitle: "Free computerized scanning",
    summary:
      "Bring your car to our B-17 workshop for a free computerized OBD scan and a general check-up. We'll explain what we find in plain language — there's no obligation to book any repair.",
    /** ISO date-time with Pakistan offset. The countdown and auto-expiry use this. */
    endsAt: "2026-12-31T23:59:59+05:00",
    endsLabel: "31 December 2026",
    includes: [
      "Computerized OBD-II fault-code scan of the engine and supported modules",
      "Reading of stored and pending fault codes, with a plain-language explanation",
      "Visual general check-up: fluids, belts, hoses, tyres, lights and battery condition",
      "Advice on what needs attention now and what can wait",
    ],
    /** Editable terms — confirm with the business owner before launch. */
    terms: [
      "Valid until 31 December 2026 at the Auto Garage One workshop in B-17, Islamabad.",
      "One free scan and check-up per vehicle.",
      "Please book in advance through WhatsApp or phone so we can reserve a slot.",
      "Repairs, parts, advanced module programming and road tests are not included and will be quoted separately after inspection.",
      "Some vehicles or modules may not be readable with standard diagnostic equipment.",
      "Auto Garage One may update or withdraw these terms; any change will be shown on this page.",
    ],
  },

  /* ------------------------------------------------------------ Brand colors */
  /** Mirrors the CSS tokens in src/app/globals.css (@theme). Used for manifest/meta. */
  colors: {
    brand: "#3ddc4a",
    brandDeep: "#1f9e2c",
    background: "#0b0d0c",
    surface: "#141816",
    metal: "#9aa3a0",
  },

  /* -------------------------------------------------------------------- SEO */
  seo: {
    /** Google Search Console HTML-tag verification token (content of google-site-verification). */
    googleSiteVerification: "7tz4tSc9JyO2Ftq5-bGPIgLEL8pq6T7bSlWHQtWTi3w",
    defaultTitle: "Auto Garage One | Car Repair Workshop in B-17 Islamabad",
    titleTemplate: "%s | Auto Garage One",
    defaultDescription:
      "Car repair and maintenance workshop in B-17 Islamabad. EFI specialist, computerized scanning & tuning, hybrid repair, AC, brakes and suspension. Free scan until Dec 2026.",
    keywords: [
      "auto mechanic Islamabad",
      "car repair workshop Islamabad",
      "auto repair B-17 Islamabad",
      "car computerized scanning Islamabad",
      "EFI specialist Islamabad",
      "hybrid car repair Islamabad",
      "car AC repair Islamabad",
    ],
    ogImage: "/brand/og-image.jpg",
    locale: "en_PK",
    twitterHandle: "",
  },

  /* ---------------------------------------------------------------- Privacy */
  analytics: {
    /**
     * Google Analytics 4 measurement ID (e.g. "G-XXXXXXX"). Leave empty to load no
     * analytics at all — in that case no cookie banner is shown because the site
     * sets no non-essential cookies.
     */
    ga4Id: "",
  },

  /** Controls the delayed, dismissible offer reminder. */
  promoPopup: { enabled: true, delaySeconds: 25 },

  /** Last date the legal pages were reviewed. */
  legalUpdated: "2026-09-23",
} as const;

/**
 * Things the business owner still needs to confirm or supply.
 * Surfaced in CLIENT-CHECKLIST.md — keep the two in sync.
 */
export const pendingConfirmation = [
  "Business email address (client.email)",
  "Direct Google \"write a review\" link (client.googleReviewUrl currently opens the Maps listing)",
  "Whether emergency breakdown assistance is offered (services.ts → emergency-breakdown-assistance)",
  "Offer terms and eligibility (client.offer.terms)",
  "More workshop photographs (repairs in progress, before & after)",
  "Technician names, qualifications and experience (About page)",
  "Final domain name (client.siteUrl)",
] as const;

export const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || client.siteUrl).replace(/\/$/, "");

export const fullAddress = [client.address.street, client.address.area, client.address.city, client.address.country]
  .filter(Boolean)
  .join(", ");
